Catch ALL errors from Protelis
Protelis can throw NoSuchMethodError which is a Throwable, but not an Exception. We need to log ALL errors and halt execution on them.